export const hostels = [
    {
        id: "1",
        image: "boys-hostel1.png",
        name: "Sunrise Boys PG",
        location: "Madhapur, Hyderabad",
        stars: 4,
        offer1: "Power Backup",
        offer2: "Gym Facility",
        offer3: "Daily Cleaning",
        offer4: "High-Speed WiFi",
        offer5: "Food Included",
        offer6: "24x7 Security",
        review_score: 7.5,
        reviews: 8912,
        old_price: 5500,
        discount: -30,
        price: 3850,
        gender: "Male",
        category: "PG"
    },
    {
        id: "2",
        image: "boys-hostel2.png",
        name: "Green Nest Boys PG",
        location: "Gachibowli, Hyderabad",
        stars: 4,
        offer1: "24x7 Security",
        offer2: "High-Speed Internet",
        offer3: "Parking Space",
        offer4: "Gym Access",
        offer5: "Homely Food",
        offer6: "Power Backup",
        review_score: 7.9,
        reviews: 5200,
        old_price: 6800,
        discount: -35,
        price: 4420,
        gender: "Male",
        category: "PG"

    },
    {
        id: "3",
        image: "boys-hostel3.png",
        name: "Metro Student Hostel",
        location: "Ameerpet, Hyderabad",
        stars: 3,
        offer1: "Common Study Room",
        offer2: "Refrigerator",
        offer3: "Daily Cleaning",
        offer4: "TV in Common Area",
        offer5: "WiFi",
        offer6: "Power Backup",
        review_score: 6.5,
        reviews: 4750,
        old_price: 4500,
        discount: -25,
        price: 3375,
        gender: "Male",
        category: "Hostel"

    },
    {
        id: "4",
        image: "boys-hostel4.png",
        name: "Bright Future Boys PG",
        location: "HITEC City, Hyderabad",
        stars: 4,
        offer1: "24/7 Security",
        offer2: "Fully Furnished",
        offer3: "Study Table",
        offer4: "Gym",
        offer5: "High-Speed Internet",
        offer6: "Food Included",
        review_score: 7.2,
        reviews: 4300,
        old_price: 7200,
        discount: -30,
        price: 5040,
        gender: "Male",
        category: "PG"

    },
    {
        id: 5,
        image: "boys-hostel5.png",
        name: "Student Comfort PG",
        location: "KPHB, Hyderabad",
        stars: 4,
        offer1: "Hot Water",
        offer2: "CCTV",
        offer3: "Daily Cleaning",
        offer4: "High-Speed WiFi",
        offer5: "Gym",
        offer6: "Study Area",
        review_score: 7.8,
        reviews: 4600,
        old_price: 6500,
        discount: -30,
        price: 4550,
        gender: "Male",
        category: "PG"
    },
    {
        id: 6,
        image: "boys-hostel6.png",
        name: "Royal Men's Hostel",
        location: "Mehdipatnam, Hyderabad",
        stars: 4,
        offer1: "AC Rooms",
        offer2: "Daily Meals",
        offer3: "Study Area",
        offer4: "24x7 Water Supply",
        offer5: "High-Speed WiFi",
        offer6: "Laundry Service",
        review_score: 8.0,
        reviews: 5100,
        old_price: 8000,
        discount: -35,
        price: 5200,
        gender: "Male",
        category: "Hostel"
    },
    {
        id: 7,
        image: "boys-hostel7.png",
        name: "City View Boys PG",
        location: "Kukatpally, Hyderabad",
        stars: 4,
        offer1: "Food Included",
        offer2: "Laundry Service",
        offer3: "AC & Non-AC Rooms",
        offer4: "Parking",
        offer5: "Free WiFi",
        offer6: "Study Table",
        review_score: 7.4,
        reviews: 4300,
        old_price: 7500,
        discount: -30,
        price: 5250,
        gender: "Male",
        category: "PG"
    },
    {
        
        id: 8,
        image: "boys-hostel8.png",
        name: "NextGen Boys PG",
        location: "Ameerpet, Hyderabad",
        stars: 5,
        offer1: "Single & Sharing Rooms",
        offer2: "Daily Cleaning",
        offer3: "Gym",
        offer4: "Food Included",
        offer5: "Free WiFi",
        offer6: "AC Rooms",
        review_score: 9.1,
        reviews: 6200,
        old_price: 9500,
        discount: -40,
        price: 5700,
        gender: "Male",
        category: "PG"
    },
    {
        id: 9,
        image: "boys-hostel9.png",
        name: "Elite Men’s Hostel",
        location: "SR Nagar, Hyderabad",
        stars: 5,
        offer1: "Security Guards",
        offer2: "Free Breakfast",
        offer3: "Study Room",
        offer4: "WiFi",
        offer5: "Power Backup",
        offer6: "24/7 Security",
        review_score: 8.3,
        reviews: 5500,
        old_price: 8500,
        discount: -35,
        price: 5525,
        gender: "Male",
        category: "Hostel"
    },
    {
        id: 10,
        image: "boys-hostel10.png",
        name: "Prime Stay Boys PG",
        location: "Gachibowli, Hyderabad",
        stars: 4,
        offer1: "Laundry",
        offer2: "Study Table",
        offer3: "High-Speed Internet",
        offer4: "Daily Meals",
        offer5: "24/7 Security",
        offer6: "Common Lounge",
        review_score: 7.9,
        reviews: 4900,
        old_price: 7800,
        discount: -30,
        price: 5460,
        gender: "Male",
        category: "PG"
    },
    {
        id: 11,
        image: "girls-hostel1.png",
        name: "Galaxy Women's Hostel",
        location: "Banjara Hills, Hyderabad",
        stars: 5,
        offer1: "24 Hours Water",
        offer2: "CCTV Cameras",
        offer3: "Hot Water",
        offer4: "Free WiFi",
        offer5: "Homely Food",
        offer6: "Washing Machine",
        review_score: 5.9,
        reviews: 10524,
        old_price: 6888,
        discount: -45,
        price: 3763,
        gender: "Female",
        category: "Hostel"
    },
    {
        id: 12,
        image: "girls-hostel2.png",
        name: "Elite Girls PG",
        location: "Gachibowli, Hyderabad",
        stars: 4,
        offer1: "Security",
        offer2: "Housekeeping",
        offer3: "High-Speed WiFi",
        offer4: "Power Backup",
        offer5: "Study Room",
        offer6: "Gym",
        review_score: 7.2,
        reviews: 8100,
        old_price: 7450,
        discount: -35,
        price: 4843,
        gender: "Female",
        category: "PG"
    },{
        id: 13,
        image: "girls-hostel3.png",
        name: "Comfort Women's PG",
        location: "Madhapur, Hyderabad",
        stars: 4,
        offer1: "24/7 Security",
        offer2: "Daily Cleaning",
        offer3: "Home-Cooked Meals",
        offer4: "Free Laundry",
        offer5: "Study Desk",
        offer6: "WiFi",
        review_score: 7.8,
        reviews: 5700,
        old_price: 6500,
        discount: -30,
        price: 4550,
        gender: "Female",
        category: "PG"
    },
    {
        id: 14,
        image: "girls-hostel4.png",
        name: "Maple Leaf Girls Hostel",
        location: "Ameerpet, Hyderabad",
        stars: 3,
        offer1: "Common Lounge",
        offer2: "WiFi",
        offer3: "High Security",
        offer4: "AC & Non-AC Rooms",
        offer5: "Parking",
        offer6: "Daily Meals",
        review_score: 6.5,
        reviews: 4750,
        old_price: 5500,
        discount: -25,
        price: 4125,
        gender: "Female",
        category: "Hostel"
    },
    {
        id: 15,
        image: "girls-hostel5.png",
        name: "Urban Nest Co-Living",
        location: "HITEC City, Hyderabad",
        stars: 4,
        offer1: "High-Speed Internet",
        offer2: "Common Study Area",
        offer3: "Gym",
        offer4: "Food Service",
        offer5: "Housekeeping",
        offer6: "Laundry",
        review_score: 7.9,
        reviews: 6000,
        old_price: 7500,
        discount: -30,
        price: 5250,
        gender: "Female",
        category: "PG"
    },
    {
        id: 16,
        image: "girls-hostel6.png",
        name: "Safe Haven Girls PG",
        location: "Mehdipatnam, Hyderabad",
        stars: 4,
        offer1: "Biometric Security",
        offer2: "Power Backup",
        offer3: "Free WiFi",
        offer4: "Personal Lockers",
        offer5: "Homely Meals",
        offer6: "Study Table",
        review_score: 8.2,
        reviews: 5100,
        old_price: 7000,
        discount: -35,
        price: 4550,
        gender: "Female",
        category: "PG"
    },
    {
        id: 17,
        image: "girls-hostel7.png",
        name: "Sunshine Women's Hostel",
        location: "Kukatpally, Hyderabad",
        stars: 4,
        offer1: "Homely Food",
        offer2: "AC & Non-AC Rooms",
        offer3: "Daily Cleaning",
        offer4: "Laundry Service",
        offer5: "WiFi",
        offer6: "24x7 Security",
        review_score: 7.4,
        reviews: 4300,
        old_price: 6000,
        discount: -30,
        price: 4200,
        gender: "Female",
        category: "Hostel"
    },{
        id: 18,
        image: "girls-hostel8.png",
        name: "Diamond Girls PG",
        location: "Ameerpet, Hyderabad",
        stars: 5,
        offer1: "Fully Furnished Rooms",
        offer2: "Free Breakfast",
        offer3: "High-Speed Internet",
        offer4: "Housekeeping",
        offer5: "Daily Meals",
        offer6: "Gym",
        review_score: 8.9,
        reviews: 6800,
        old_price: 9000,
        discount: -40,
        price: 5400,
        gender: "Female",
        category: "PG"
    },
    {
        id: 18,
        image: "girls-hostel8.png",
        name: "Diamond Girls PG",
        location: "Ameerpet, Hyderabad",
        stars: 5,
        offer1: "Fully Furnished Rooms",
        offer2: "Free Breakfast",
        offer3: "High-Speed Internet",
        offer4: "Housekeeping",
        offer5: "Daily Meals",
        offer6: "Gym",
        review_score: 8.9,
        reviews: 6800,
        old_price: 9000,
        discount: -40,
        price: 5400,
        gender: "Female",
        category: "PG"
    },
    {
        id: 19,
        image: "girls-hostel9.png",
        name: "Pearl Residency Women's PG",
        location: "SR Nagar, Hyderabad",
        stars: 5,
        offer1: "Study Area",
        offer2: "Security Guards",
        offer3: "High-Speed WiFi",
        offer4: "Daily Meals",
        offer5: "Laundry Service",
        offer6: "Free Parking",
        review_score: 8.4,
        reviews: 5500,
        old_price: 8000,
        discount: -35,
        price: 5200,
        gender: "Female",
        category: "PG"
    },
    {
        id: 20,
        image: "girls-hostel10.png",
        name: "Prime Stay Girls PG",
        location: "Gachibowli, Hyderabad",
        stars: 4,
        offer1: "24/7 Security",
        offer2: "Study Table",
        offer3: "Laundry",
        offer4: "Daily Cleaning",
        offer5: "Food Included",
        offer6: "Power Backup",
        review_score: 7.7,
        reviews: 4900,
        old_price: 7000,
        discount: -30,
        price: 4900,
        gender: "Female",
        category: "PG"
    },
    {
        id: 21,
        image: "guest-in1.png",
        name: "Urban Stay Guest-In",
        location: "Banjara Hills, Hyderabad",
        stars: 5,
        offer1: "Free Breakfast",
        offer2: "High-Speed WiFi",
        offer3: "Daily Housekeeping",
        offer4: "Gym",
        offer5: "24x7 Security",
        review_score: 8.9,
        reviews: 7200,
        old_price: 5500,
        discount: -20,
        price: 4400,
        category: "Guest-In"
    },
    {
        id: 22,
        image: "guest-in2.png",
        name: "Comfort Zone Guest-In",
        location: "Gachibowli, Hyderabad",
        stars: 4,
        offer1: "AC Rooms",
        offer2: "Free Parking",
        offer3: "Laundry Service",
        offer4: "Food Included",
        offer5: "WiFi",
        review_score: 8.2,
        reviews: 5100,
        old_price: 6200,
        discount: -25,
        price: 4650,
        category: "Guest-In"
    },
    {
        id: 23,
        image: "guest-in3.png",
        name: "Elite Residency",
        location: "Madhapur, Hyderabad",
        stars: 5,
        offer1: "Hot Water",
        offer2: "CCTV Security",
        offer3: "Room Service",
        offer4: "Gym",
        offer5: "Complimentary Meals",
        review_score: 9.1,
        reviews: 6500,
        old_price: 7500,
        discount: -30,
        price: 5250,
        category: "Guest-In"
    },
    {
        id: 24,
        image: "guest-in4.png",
        name: "Cozy Stay Guest House",
        location: "Ameerpet, Hyderabad",
        stars: 4,
        offer1: "Fully Furnished",
        offer2: "High-Speed WiFi",
        offer3: "Housekeeping",
        offer4: "24x7 Security",
        offer5: "Power Backup",
        review_score: 7.5,
        reviews: 4800,
        old_price: 5800,
        discount: -20,
        price: 4640,
        category: "Guest-In"
    },
    {
        id: 25,
        image: "guest-in5.png",
        name: "Green Leaf Guest-In",
        location: "Kondapur, Hyderabad",
        stars: 5,
        offer1: "Breakfast Included",
        offer2: "Laundry",
        offer3: "WiFi",
        offer4: "Parking",
        offer5: "Daily Housekeeping",
        review_score: 8.6,
        reviews: 5900,
        old_price: 6700,
        discount: -30,
        price: 4690,
        category: "Guest-In"
    },
    {
        id: 26,
        image: "guest-in6.png",
        name: "Sapphire Residency",
        location: "Kukatpally, Hyderabad",
        stars: 4,
        offer1: "AC & Non-AC Rooms",
        offer2: "Free WiFi",
        offer3: "Power Backup",
        offer4: "24/7 Security",
        offer5: "Laundry Service",
        review_score: 7.9,
        reviews: 5300,
        old_price: 6200,
        discount: -25,
        price: 4650,
        category: "Guest-In"
    },
    {
        id: 27,
        image: "guest-in7.png",
        name: "Pearl Haven Guest-In",
        location: "Mehdipatnam, Hyderabad",
        stars: 5,
        offer1: "Single & Sharing Rooms",
        offer2: "Daily Cleaning",
        offer3: "High-Speed WiFi",
        offer4: "Power Backup",
        offer5: "24/7 Reception",
        review_score: 9.0,
        reviews: 6800,
        old_price: 7800,
        discount: -35,
        price: 5070,
        category: "Guest-In"
    },
    {
        id: 28,
        image: "guest-in8.png",
        name: "Cityscape Guest House",
        location: "Secunderabad, Hyderabad",
        stars: 4,
        offer1: "Free Breakfast",
        offer2: "Hot Water",
        offer3: "Gym",
        offer4: "CCTV",
        offer5: "24x7 Security",
        review_score: 8.1,
        reviews: 5600,
        old_price: 6500,
        discount: -30,
        price: 4550,
        category: "Guest-In"
    },
    {
        id: 29,
        image: "guest-in9.png",
        name: "Bliss Inn",
        location: "SR Nagar, Hyderabad",
        stars: 4,
        offer1: "AC Rooms",
        offer2: "Parking",
        offer3: "Food Included",
        offer4: "Housekeeping",
        offer5: "WiFi",
        review_score: 7.7,
        reviews: 4900,
        old_price: 5900,
        discount: -25,
        price: 4425,
        category: "Guest-In"
    },
    {
        id: 30,
        image: "guest-in10.png",
        name: "Prime Stay Guest House",
        location: "HITEC City, Hyderabad",
        stars: 5,
        offer1: "Security",
        offer2: "Fully Furnished",
        offer3: "WiFi",
        offer4: "Laundry",
        offer5: "Parking",
        review_score: 9.2,
        reviews: 7000,
        old_price: 7200,
        discount: -30,
        price: 5040,
        category: "Guest-In"
    }
];